---
title: "TPM plotter"
author: "Carlos Perez-Cervantes"
date: "2024-07-07"
output:
  html_document: default
  self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
user=Sys.info()[["user"]]
setwd( paste0("/project/imoskowitz/",user ))

```



#### load libraries create function
```{r, message=FALSE}

library(tidyverse, lib.loc="/project/imoskowitz/cperez5/software/R_libs/x86_64-pc-linux-gnu-library/4.3/")
library(readxl, lib.loc="/project/imoskowitz/cperez5/software/R_libs/x86_64-pc-linux-gnu-library/4.3/")
library(ggpubr, lib.loc="/project/imoskowitz/cperez5/software/R_libs/x86_64-pc-linux-gnu-library/4.3/")


plotTPM <- function(seqid = "", 
                    genesToPlot = c("Gli1","Hhip","Ptch1"), 
                    pathToSample = "",
                    colorBy = "Genotype") {
  require(tidyverse)
  require(readxl)
  
  tpmfile <- read_tsv(
    paste0("/project/imoskowitz/shared/sequencing.processed/",seqid,"/star_salmon/salmon.merged.gene_tpm.tsv")
  ) %>%
    dplyr::select(-gene_name) %>%
    subset(. , grepl( paste(genesToPlot, collapse = "$|"), gene_id, ignore.case=T)) %>%
    gather(run_sample,TPM,-gene_id)
  
  sample_info <- read_excel(pathToSample) %>% 
    .[-c(2,1),] %>%
    data.frame() %>%
    dplyr::select(Experiment.ID, Sample.ID, Sample.name,Genotype,Age.stage, Treatment.protocol) %>%
    .[complete.cases(.),] %>%
    head(-1) %>%
    unite(col=run_sample, sep = "_", Experiment.ID:Sample.ID) %>%
    mutate(condition = str_sub(.$Sample.name, end = -3)) %>%
    mutate(condition = gsub(.$condition, pattern= " ", replacement=""))

  forplot <- merge(tpmfile, sample_info)
  
p <-   ggline(forplot, x = "Age.stage", y = "TPM",
            facet.by = "gene_id",
            ylab = "TPM",
            size = 2,
            color = colorBy,add = c("mean_se", "jitter"),
           ggtheme = theme_minimal(base_size= 20)
            )
facet(p, facet.by = "gene_id",scales = "free")
}



```


#### plot TPM
Change sequencing id, and matching sample sheet as needed. "colorby" parameter is
from the sample sheet; it could be Genotype, Age/stage etc
```{r, message=FALSE, fig.width=12, fig.height=12}

seqid = "20240615_LH00315_0209_A22KFLMLT3-IM-SAB-RS72"
pathToSample = "/project/imoskowitz/shared/metasheets/sample_sheets/SAB02_Sample_metasheet.xlsx"
genesToPlot = c("Gli1","Hhip","Ptch1")

plotTPM(seqid = seqid,
        genesToPlot = genesToPlot,
        pathToSample = pathToSample,
        colorBy = "Genotype") ## column from sample sheet


```







